### ISSUE TITLE
Installation, Usage, and Reference Materials

### ISSUE THREAD

**Issue by sfsdfc** [Harnesser/tiny-spice-rs#1]
Hello, I would like to inquire about tinyspice. Could you please provide instructions on how to install and use the circuit simulator? Additionally, I'm curious to know if there were any specific reference materials or books that you consulted while developing TinySPICE?

**Comment by Harnesser** [comment]
Hi there - thanks for the interest!

I've updated the README with more instructions. Links to references can be found in the openoffice file Tiny-Spice_Circuit_Simulation.fodt in the docs folder.
